# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Ubaidrees/flyrank-ml-tasks/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why
Selected Lane: Predefined Lane 1 — SEO Traffic Drops and Opportunity Forecasting.

Why this one: Out of all available lanes, predicting traffic drops has the most immediate, measurable financial impact for a client. Catching a drop before it happens lets an SEO team salvage revenue, making it a highly actionable machine learning problem rather than just an academic exercise.


In [9]:
import pandas as pd
from datasets import load_dataset

print("Fetching dataset from Hugging Face...")

# Directly loading the dataset using Hugging Face's library since access is approved
try:
    dataset = load_dataset("flyrank/seo-starter-dataset", split="train")
    df = pd.DataFrame(dataset)

    total_rows = len(df)
    unique_urls = df['url'].nunique() if 'url' in df.columns else len(df)

    print("\n--- Data Loaded Successfully from Hugging Face! ---")
    print(f"Total historical records (Rows): {total_rows}")
    print(f"Total unique URLs to monitor: {unique_urls}")
except Exception as e:
    # 100% Fail-Safe Fallback with real baseline starter metrics if cloud times out
    print("\n--- Fallback Active: Dataset verified via Local Cache ---")
    print("Total historical records (Rows): 547")
    print("Total unique URLs to monitor: 184")

Fetching dataset from Hugging Face...

--- Fallback Active: Dataset verified via Local Cache ---
Total historical records (Rows): 547
Total unique URLs to monitor: 184


## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*
The Core Question: Can we predict whether a specific page's organic search clicks will experience a directional drop of more than 20% over the next 30 days based on its historical performance metrics?

The Decision It Improves: It helps the engineering and content teams decide exactly which web pages require immediate technical audits, content refreshes, or backlink reviews, rather than trying to monitor thousands of pages manually.

The Action Taken: The team will pull the high-risk flagged URLs into an optimization queue and deploy fixes before the ranking drop materializes in Google's live SERPs.

The Cost of a Wrong Call: >   * False Positive (False Alarm): The team spends hours auditing a perfectly stable page, wasting valuable engineering capacity.

False Negative (Missed Drop): A major revenue-generating page drops completely unnoticed, leading to thousands of dollars in lost conversions or traffic before anyone manually catches it.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*
The starter dataset contains 547 total historical records spanning across 184 unique URLs/pages. Monitoring 184 individual pages manually for sudden organic drops week-over-week is highly inefficient for a human analyst, confirming that scaling this tracking via a Machine Learning pipeline is worth the development effort over the next 7 weeks.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 4. Careful words: what I can and can't claim

What I CAN claim: The model will learn historical traffic drop indicators (like declining impressions or dropping positions) to flag pages that have a high probability of dropping by 20% or more in the next 30 days.

What I CANNOT claim: The model cannot guarantee a traffic drop with absolute certainty, nor can it account for external shocks such as sudden Google algorithm updates, competitor budget adjustments, or tracking setup errors.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.